### PR TITLE
Make it compile!

### PR DESCRIPTION
**Pull request by facekapow**
Updates the C++ code to use the latest version of `nan` (actually, all of the dependencies have been updated to the latest versions), which makes it compilable again (I've only tested on node v6). I'm not a C++ master, so there's probably a lot of issues in the readability and efficiency department but it works! 😄

I've based my fork off of another fork, which in turn was based on another fork, so they deserve some credit too 😉 : @perint, and @tcr

### CODE REVIEW

**Comment by facekapow** [comment]
BTW, you might want to update the Travis Node.js version

**Comment by tcr** [comment]
Nice work @facekapow!

@Floby, would you be interested in merging these, or perhaps enable commit access to @facekapow to be able to merge them? Thanks for your input :)

**Comment by Floby** [comment]
Hello,
I tried runing this code, but unfortunately Spotify removed all download links from their website for libspotify https://developer.spotify.com/technologies/libspotify/#libspotify-and-cocoalibspotify-downloads
:(

**Comment by Floby** [comment]
managed to find a version of it.
This does compile but my tests are failing :D 
I'll have to see if this is expected or not, since the library as a whole has been deprecated by spotify

**Comment by Floby** [comment]
Hello, the libspotify binary is less stable than every, but this does compile and is able to play some sound, so I guess this is enough \o/

Thank all of you for doing the effort of making it compile again!

**Comment by facekapow** [comment]
@Floby :+1:

**Pull request merged**
